import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import Image from "next/image";
import Sandie from "public/SandyAvatar.png";


export default function Home() {
  return (
    <>
      <Head>
        <title>Enuma Sandra Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons">SandieCodes</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer text-2xl" />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium">Sandra Enuma</h2>
            <h3 className="text-2xl py-2">Web Developer</h3>
            <p className="text-md py-5 leading-8 text-gray-800">
              Frontend focused web developer providing services for any website and
              web application frontend need. Join me down below and let's
              connect!
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillGithub />
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden"> 
<Image src={Sandie} style={{layout: "fill", objectFit: "cover"}} alt="Dev Image" />
          </div>
        </section>

        {/* 2nd page */}

        <section>
          <div>
            <h3 className="text-3xl py-1">Services I offer</h3>
          <p className="text-md py-2 leading-2 text-gray-800">
          As a frontend developer, I hope to work for
              <span className="text-teal-500"> agencies </span> and <span className="text-teal-500">startups </span> 
              where I can contribute, learn and grow.
              I also wish to collaborate with other talented people to create amazing digital products
              for both business and consumer use.
          </p>
          </div>
        </section>
      </main>
    </>
  );
}
